# Generated by Django 3.2.5 on 2021-07-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('tops', 'Tops'), ('pants', 'Pants'), ('shoes', 'Shoes')], default='Tops', max_length=5),
        ),
    ]
