# Generated by Django 3.2.5 on 2021-07-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_countries_billingaddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='same_billing_address',
        ),
    ]
