# Generated by Django 3.2.5 on 2021-07-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_favorite'),
        ('post', '0006_alter_review_post'),
    ]

    operations = [
    ]
