# Generated by Django 3.2.5 on 2021-07-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_merge_0004_post_favorite_0006_alter_review_post'),
        ('post', '0008_auto_20210720_1557'),
    ]

    operations = [
    ]
