# Generated by Django 3.2.5 on 2021-07-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_merge_20210720_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
