# Generated by Django 3.2.5 on 2021-07-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20210720_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='MorF',
            field=models.CharField(default='Male or Female', max_length=64),
        ),
    ]
