# Generated by Django 3.2.5 on 2021-07-21 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0010_auto_20210720_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
