# Generated by Django 3.2.5 on 2021-07-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20210721_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='MorF',
            field=models.CharField(default='Male or Female', max_length=6),
        ),
    ]
