# Generated by Django 3.2.5 on 2021-07-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
