# Generated by Django 3.2.5 on 2021-07-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
