# Generated by Django 3.2.5 on 2021-07-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_post_morf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='MorF',
            field=models.CharField(default='Male', max_length=6),
        ),
    ]
