# Generated by Django 3.2.5 on 2021-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_post_morf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='MorF',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=6),
        ),
    ]
