# Generated by Django 3.2.5 on 2021-07-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_post_price'),
        ('post', '0014_alter_post_morf'),
    ]

    operations = [
    ]
