# Generated by Django 3.2.5 on 2021-07-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_delete_product'),
        ('post', '0015_merge_0012_alter_post_price_0014_alter_post_morf'),
    ]

    operations = [
    ]
