# Generated by Django 3.2.5 on 2021-07-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_merge_20210722_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='MorF',
            new_name='gender',
        ),
    ]
