# Generated by Django 3.2.5 on 2021-07-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_merge_20210723_1318'),
        ('post', '0017_rename_morf_post_gender'),
    ]

    operations = [
    ]
