# Generated by Django 3.2.5 on 2021-07-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_merge_20210723_1926'),
        ('post', '0017_rename_morf_post_gender'),
    ]

    operations = [
    ]
