# Generated by Django 3.2.5 on 2021-07-26 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_merge_20210723_1928'),
        ('post', '0018_merge_20210726_2056'),
    ]

    operations = [
    ]
