# Generated by Django 3.2.5 on 2021-07-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_merge_20210722_1357'),
        ('post', '0019_merge_20210726_2109'),
    ]

    operations = [
    ]
