# Generated by Django 3.2.5 on 2021-07-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_merge_20210728_1349'),
        ('post', '0021_alter_post_description'),
    ]

    operations = [
    ]
